# Generated by Django 5.0.7 on 2025-07-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('created_on', models.DateTimeField()),
                ('views', models.IntegerField(default=0)),
                ('repository', models.URLField(blank=True, default=None, null=True)),
                ('youtube_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
