# Generated by Django 5.2.4 on 2025-08-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='ifdjfdf', max_length=255),
            preserve_default=False,
        ),
    ]
